-- ============================================================================
-- DEMO / THROWAWAY  -- Siembra de KPIs para visualizar vectores (Momento 1)
-- ----------------------------------------------------------------------------
-- Fuente: infrastructure/postgres/init/_disabled/04_seed.sql (columnas antiguas
-- nombrekpi/descripcion/direccion_deseada/razon/formula). Remapeado a las
-- columnas REALES de tt_rag.kpi: nombre_kpi, descripcion, categoria, ambito,
-- url_documentacion, formula.
--   nombrekpi        -> nombre_kpi
--   descripcion+razon-> descripcion
--   direccion_deseada-> plegado en ambito ("Dirección deseada: ...")
--   formula          -> formula
--   categoria        -> tema asignado (Académico / Financiero / Investigación /
--                       Experiencia estudiantil / Reputación / Operación)
-- Idempotente: TRUNCATE + RESTART IDENTITY. NO inserta en 'variable'.
-- Datos de demostración; se reemplazarán por los KPIs reales más adelante.
-- ============================================================================
SET search_path TO tt_rag, public;

TRUNCATE tt_rag.kpi RESTART IDENTITY CASCADE;

INSERT INTO kpi (nombre_kpi, descripcion, categoria, ambito, formula) VALUES
('Estatus de Acreditación y Rankings', 'El número y estatus de las acreditaciones, y la posición en rankings educativos, es indicador de reputación y calidad. Razón: más acreditaciones vigentes y mejor posición reflejan mayor reputación y calidad institucional.', 'Reputación', 'Dirección deseada: Aumentar', 'Tasa_Acreditacion = num_accreditations_activas / num_accreditations_totales; Percentil_Ranking = (1 - (posicion_ranking / total_instituciones_en_ranking)) * 100'),
('Selectividad de Admisión', 'El porcentaje de solicitantes admitidos es señal de reputación y atractivo. Una tasa más baja indica mayor selectividad. Razón: una tasa de admisión más baja indica mayor selectividad y prestigio percibido.', 'Reputación', 'Dirección deseada: Disminuir', 'Tasa_Admision (%) = (num_admitidos / num_solicitantes) * 100'),
('Tasa de Donación de Exalumnos', 'La tasa a la que los exalumnos donan es indicador de satisfacción a largo plazo y componente crítico de ingresos. Razón: una mayor tasa refleja satisfacción sostenida y fortalece ingresos.', 'Financiero', 'Dirección deseada: Aumentar', 'Tasa_Donacion_Exalumnos (%) = (num_alumni_donantes / num_alumni_totales) * 100'),
('Tasas de Asistencia', 'Indicador temprano del compromiso y satisfacción del estudiante, correlacionado con éxito académico. Razón: mayor asistencia se asocia con mayor compromiso y mejores resultados.', 'Experiencia estudiantil', 'Dirección deseada: Aumentar', 'Tasa_Asistencia (%) = (dias_asistidos_totales / dias_clase_programados_totales) * 100'),
('Tamaño Promedio de Clase', 'Número promedio de estudiantes por clase; indica el nivel de atención individual posible. Razón: clases más pequeñas permiten mayor atención individualizada.', 'Académico', 'Dirección deseada: Disminuir', 'Tamano_Promedio_Clase = num_estudiantes_totales / num_clases_totales'),
('Colegiatura Promedio', 'Costo promedio de colegiatura; indica el posicionamiento de mercado. Razón: el nivel adecuado depende del posicionamiento estratégico, no es inherentemente bueno subir o bajar sin contexto.', 'Financiero', 'Dirección deseada: Monitorear', 'Colegiatura_Promedio = suma_colegiaturas_cobradas / num_estudiantes_totales'),
('Años Promedio hasta Graduación', 'Tiempo promedio para completar el programa; indica dificultad, flexibilidad y eficiencia. Razón: menor tiempo indica mayor eficiencia del programa y de la institución.', 'Académico', 'Dirección deseada: Disminuir', 'Anios_Promedio_Graduacion = suma_anios_hasta_graduacion_por_estudiante / num_graduados_totales'),
('Puntajes de Exámenes de Referencia', 'Puntajes promedio en exámenes como SAT/ACT/GMAT; señalan la capacidad académica del cuerpo estudiantil. Razón: puntajes más altos reflejan mayor capacidad académica.', 'Académico', 'Dirección deseada: Aumentar', 'Puntaje_Promedio_Examen = suma_puntajes_examen / num_estudiantes_evaluados'),
('Estadísticas de Seguridad del Campus', 'La tasa de delitos en el campus es medida crítica del bienestar estudiantil y de reputación. Razón: menor tasa de incidentes refleja un campus más seguro.', 'Operación', 'Dirección deseada: Disminuir', 'Tasa_Delitos_Campus = (num_incidentes_seguridad / poblacion_campus_total) * 1000'),
('Razón de Consejeros por Estudiante', 'Indica el nivel de apoyo en planeación académica y temas socioemocionales. Razón: una razón más baja implica mayor disponibilidad de apoyo individual.', 'Experiencia estudiantil', 'Dirección deseada: Disminuir', 'Razon_Consejero_Estudiante = num_estudiantes_totales / num_consejeros'),
('Tasa de Finalización de Cursos (Educación en Línea)', 'Porcentaje de estudiantes que completan un curso en línea respecto al total inscrito. Razón: mayor tasa indica mejor diseño y efectividad del curso en línea.', 'Académico', 'Dirección deseada: Aumentar', 'Tasa_Finalizacion_Online (%) = (num_estudiantes_que_completan_curso_online / num_estudiantes_inscritos_curso_online) * 100'),
('Razón de Inscripción a Finalización de Curso', 'Estudiantes que completan un curso vs. los inscritos; razón alta indica contenido atractivo y valor. Razón: una razón más alta indica un curso más atractivo y de mayor valor percibido.', 'Académico', 'Dirección deseada: Aumentar', 'Razon_Inscripcion_Finalizacion = num_estudiantes_completan_curso / num_estudiantes_inscritos_curso'),
('Tasas de Incumplimiento en Préstamos Estudiantiles', 'Una tasa más baja indica estabilidad financiera de egresados y valor de la educación. Razón: menor tasa refleja mejor estabilidad financiera y mayor valor percibido.', 'Financiero', 'Dirección deseada: Disminuir', 'Tasa_Incumplimiento_Prestamos (%) = (num_prestamos_en_default / num_prestamos_totales_otorgados) * 100'),
('Métricas de Diversidad', 'Diversidad estudiantil y docente (raza, género, nacionalidad); indica inclusividad y atractivo. Razón: mayor diversidad refleja inclusividad y atractivo para una demografía amplia.', 'Experiencia estudiantil', 'Dirección deseada: Aumentar', 'Proporcion_Diversidad_X (%) = (num_estudiantes_grupo_demografico_x / num_estudiantes_totales) * 100'),
('Tasa de Deserción', 'Porcentaje de estudiantes que abandonan antes de completar; tasa alta indica insatisfacción o dificultad. Razón: menor tasa indica mayor satisfacción y menos problemas institucionales.', 'Experiencia estudiantil', 'Dirección deseada: Disminuir', 'Tasa_Desercion (%) = (num_estudiantes_que_abandonan / num_estudiantes_inscritos_totales) * 100'),
('Tamaño del Fondo Patrimonial (Endowment)', 'Medida clave de salud financiera y sostenibilidad. Razón: un fondo patrimonial más grande refleja mayor salud financiera y sostenibilidad.', 'Financiero', 'Dirección deseada: Aumentar', 'Fondo_Patrimonial_por_Estudiante = valor_total_fondo_patrimonial / num_estudiantes_totales'),
('Actividades Extracurriculares', 'Número y variedad de actividades extracurriculares; indican educación integral e involucramiento. Razón: mayor participación refleja mayor compromiso con la formación integral.', 'Experiencia estudiantil', 'Dirección deseada: Aumentar', 'Tasa_Participacion_Extracurricular (%) = (num_estudiantes_participantes / num_estudiantes_totales) * 100'),
('Tasa de Publicación Docente', 'Tasa a la que el profesorado publica en revistas reconocidas; mide rigor académico e investigación. Razón: mayor tasa refleja mayor rigor académico y enfoque en investigación.', 'Investigación', 'Dirección deseada: Aumentar', 'Tasa_Publicacion_Docente = num_publicaciones_indexadas / num_profesores_investigadores'),
('Calificación del Profesorado y Tasa de Rotación', 'La calidad y estabilidad del profesorado indican salud institucional. Razón: se busca aumentar la proporción de profesores altamente calificados y disminuir la rotación.', 'Académico', 'Dirección deseada: Mixto', 'Tasa_Calificacion_Docente (%) = (num_profesores_altamente_calificados / num_profesores_totales) * 100; Tasa_Rotacion_Docente (%) = (num_profesores_que_se_van / num_profesores_promedio_periodo) * 100'),
('Producción de Investigación Docente', 'Número y calidad de artículos y producción de investigación; indica nivel intelectual y prestigio. Razón: mayor producción y calidad refleja mayor prestigio institucional.', 'Investigación', 'Dirección deseada: Aumentar', 'Produccion_Investigacion_por_Docente = num_publicaciones_totales / num_profesores_investigadores; Citas_Promedio_por_Publicacion = num_citas_totales / num_publicaciones_totales'),
('Tasa de Graduación', 'Porcentaje de estudiantes que completan su programa en un periodo; señala currículo sólido y enseñanza efectiva. Razón: mayor tasa refleja un currículo sólido y métodos efectivos.', 'Académico', 'Dirección deseada: Aumentar', 'Tasa_Graduacion (%) = (num_estudiantes_graduados_en_periodo / num_estudiantes_cohorte_inicial) * 100'),
('Convenios con la Industria y Prácticas Profesionales', 'Número de convenios y prácticas; indica oportunidades prácticas e integración con el sector productivo. Razón: más convenios y vacantes amplían las oportunidades prácticas.', 'Operación', 'Dirección deseada: Aumentar', 'Tasa_Disponibilidad_Practicas (%) = (num_vacantes_practicas_ofrecidas / num_estudiantes_totales) * 100'),
('Gasto Instruccional por Estudiante (FTE)', 'Cuánto invierte la institución en servicios instruccionales por estudiante; señal de calidad educativa. Razón: mayor gasto por estudiante puede reflejar mayor inversión en calidad.', 'Financiero', 'Dirección deseada: Aumentar', 'Gasto_Instruccional_por_FTE = gasto_total_instruccional / num_estudiantes_fte'),
('Tasa de Colocación Laboral', 'Porcentaje de egresados que consiguen empleo en su área tras graduarse. Razón: mayor tasa refleja la efectividad de la institución para preparar a sus egresados.', 'Reputación', 'Dirección deseada: Aumentar', 'Tasa_Colocacion_Laboral (%) = (num_graduados_empleados_en_su_area / num_graduados_totales) * 100'),
('Recursos Bibliotecarios', 'Número y calidad de recursos de biblioteca (libros, artículos, recursos digitales). Razón: más recursos por estudiante reflejan mayor apoyo a la excelencia académica.', 'Académico', 'Dirección deseada: Aumentar', 'Recursos_Bibliotecarios_por_Estudiante = num_recursos_bibliotecarios_totales / num_estudiantes_totales'),
('Número de Programas Acreditados', 'Programas acreditados por organismos relevantes; indicador de calidad y cumplimiento de estándares. Razón: más programas acreditados reflejan mayor calidad y cumplimiento.', 'Reputación', 'Dirección deseada: Aumentar', 'Proporcion_Programas_Acreditados (%) = (num_programas_acreditados / num_programas_totales) * 100'),
('Patentes Otorgadas', 'Número de patentes otorgadas; medida de productividad de investigación e innovación. Razón: más patentes reflejan mayor productividad de investigación y capacidad de innovación.', 'Investigación', 'Dirección deseada: Aumentar', 'Patentes_por_Investigador = num_patentes_otorgadas / num_profesores_investigadores'),
('Porcentaje de Profesorado con Grado Terminal', 'Proporción de profesorado con el grado más alto (doctorado); indica calidad docente. Razón: mayor porcentaje de doctores refleja mayor calidad docente.', 'Académico', 'Dirección deseada: Aumentar', 'Tasa_Grado_Terminal (%) = (num_profesores_con_doctorado / num_profesores_totales) * 100'),
('Tasa de Retención Estudiantil', 'Porcentaje de estudiantes que se reinscriben periodo tras periodo; señala calidad y satisfacción. Razón: mayor retención refleja mejor calidad educativa y satisfacción.', 'Experiencia estudiantil', 'Dirección deseada: Aumentar', 'Tasa_Retencion (%) = (num_estudiantes_reinscritos_siguiente_periodo / num_estudiantes_elegibles_reinscripcion) * 100'),
('Puntajes de Satisfacción Estudiantil', 'Satisfacción general con la experiencia educativa, medida por encuestas (contenido, enseñanza, apoyo, instalaciones). Razón: puntajes más altos reflejan una mejor experiencia integral.', 'Experiencia estudiantil', 'Dirección deseada: Aumentar', 'Puntaje_Promedio_Satisfaccion = suma_puntajes_encuesta_satisfaccion / num_encuestas_respondidas');
