"""
Enriched Metadata Endpoints

Handles enriched metadata proposals generated after LLM analysis.
Enriched metadata adds inferred context beyond the basic 13 Dublin Core fields.

Workflow:
1. analysis-service completes LLM processing
2. analysis-service calls POST /enrichment/{id} with proposals
3. User reviews proposals via GET /enrichment/{id}
4. User approves/rejects via POST /enrichment/{id}/approve
5. State updates to "etl_pendiente_enriquecimiento"
"""

from fastapi import APIRouter, HTTPException, Depends, status, Query
from sqlalchemy.orm import Session
import logging
from typing import Optional, List, Dict

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/enrichment", tags=["enrichment"])

# Import shared dependencies
from shared.db.database import get_db

# Import business logic
from services.enrichment_engine import EnrichmentEngine


@router.post("/enrichment/{instrumento_id}/create")
async def create_enrichment_proposals(
    instrumento_id: int,
    proposals: List[dict],
    db: Session = Depends(get_db)
):
    """
    Create enriched metadata proposals (called by analysis-service after LLM).
    
    This endpoint receives enrichment proposals generated by the LLM analysis:
    - Inferred domain/subject area
    - Quality assessment
    - Data structure analysis
    - Improvement recommendations
    - Coverage assessment
    
    Proposals are stored with estado_decision = "pendiente" for user review.
    
    Request body:
    [
        {
            "tipo": "domain_inferred",
            "valor": "Educational Assessment",
            "confianza": 0.95,
            "descripcion": "LLM detected this as educational assessment instrument"
        },
        ...
    ]
    """
    try:
        result = EnrichmentEngine.create_proposals(db, instrumento_id, proposals)
        logger.info(f"✅ Created {len(proposals)} enrichment proposals for instrument {instrumento_id}")
        return {
            "instrumento_id": instrumento_id,
            "n_proposals": len(proposals),
            "status": "created",
            "message": f"{len(proposals)} enrichment proposals created and pending review"
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error creating enrichment proposals: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to create enrichment proposals"
        )


@router.get("/enrichment/{instrumento_id}")
async def get_enrichment_proposals(
    instrumento_id: int,
    filter_status: Optional[str] = Query(
        None,
        description="Filter by estado_decision: 'pendiente', 'aceptada', 'rechazada'"
    ),
    db: Session = Depends(get_db)
):
    """
    Retrieve enrichment proposals for user review.
    
    Returns all enrichment proposals with their current approval status:
    - pendiente: awaiting user decision
    - aceptada: approved and will be materialized
    - rechazada: rejected and ignored
    
    Optional filter by status for easier review.
    """
    try:
        proposals = EnrichmentEngine.get_proposals(
            db,
            instrumento_id,
            filter_status=filter_status
        )
        logger.info(f"✅ Retrieved enrichment proposals for instrument {instrumento_id}")
        
        # Count by status
        stats = {
            "pendiente": sum(1 for p in proposals if p.get("estado_decision") == "pendiente"),
            "aceptada": sum(1 for p in proposals if p.get("estado_decision") == "aceptada"),
            "rechazada": sum(1 for p in proposals if p.get("estado_decision") == "rechazada"),
        }
        
        return {
            "instrumento_id": instrumento_id,
            "n_proposals": len(proposals),
            "stats": stats,
            "proposals": proposals
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error retrieving enrichment proposals: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to retrieve enrichment proposals"
        )


@router.post("/enrichment/{instrumento_id}/approve")
async def approve_enrichment_proposals(
    instrumento_id: int,
    decisions: Dict[int, str],  # {proposal_id: "aceptada" | "rechazada"}
    db: Session = Depends(get_db)
):
    """
    Apply user decisions to enrichment proposals (Step 4b of workflow).
    
    User provides accept/reject decisions for each enrichment proposal.
    
    Request body:
    {
        "1": "aceptada",
        "2": "rechazada",
        "3": "aceptada",
        ...
    }
    
    After all decisions are applied:
    - Accepted proposals are materialized into MetadatosEnriquecidos
    - Rejected proposals are marked but not used
    - Instrument state updates to "etl_aprobado" (ready for JSON generation)
    """
    try:
        result = EnrichmentEngine.approve_proposals(db, instrumento_id, decisions)
        logger.info(f"✅ Enrichment approved for instrument {instrumento_id}")
        
        return {
            "instrumento_id": instrumento_id,
            "n_decisions": len(decisions),
            "n_aceptadas": result.get("n_aceptadas", 0),
            "n_rechazadas": result.get("n_rechazadas", 0),
            "message": f"{result.get('n_aceptadas', 0)} proposals accepted, {result.get('n_rechazadas', 0)} rejected",
            "new_state": "etl_aprobado"
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"❌ Error approving enrichment: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to approve enrichment proposals"
        )


@router.get("/enrichment/{instrumento_id}/summary")
async def get_enrichment_summary(
    instrumento_id: int,
    db: Session = Depends(get_db)
):
    """
    Get summary statistics of enrichment proposals.
    
    Useful for dashboards showing approval progress.
    """
    try:
        summary = EnrichmentEngine.get_summary(db, instrumento_id)
        logger.info(f"✅ Enrichment summary retrieved for instrument {instrumento_id}")
        return summary
    except Exception as e:
        logger.error(f"❌ Error retrieving enrichment summary: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to retrieve enrichment summary"
        )
