"""
Enrichment Engine - Enriched Metadata Proposals

Manages proposals generated by LLM analysis:
- Storage of enriched metadata proposals
- Approval/rejection workflow
- Materialization of accepted proposals
"""

from sqlalchemy.orm import Session
from fastapi import HTTPException, status
from datetime import datetime, timezone
import logging
from typing import List, Dict, Optional

logger = logging.getLogger(__name__)


class EnrichmentEngine:
    """Business logic for enriched metadata management"""
    
    @staticmethod
    def create_proposals(
        db: Session,
        instrumento_id: int,
        proposals: List[Dict]
    ) -> dict:
        """
        Create enrichment proposals from LLM analysis.
        
        Called by analysis-service after completing LLM processing.
        Stores proposals with estado_decision = "pendiente".
        
        Proposal structure:
        {
            "tipo": "domain_inferred" | "quality" | "coverage" | etc,
            "valor": "...",
            "confianza": 0.0-1.0,
            "descripcion": "..."
        }
        """
        from shared.models.instrumento_procesado import InstrumentoProcesado
        
        # Verify instrument exists
        instrumento = db.query(InstrumentoProcesado).filter(
            InstrumentoProcesado.instrumento_id == instrumento_id
        ).first()
        
        if not instrumento:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Instrument {instrumento_id} not found"
            )
        
        # TODO: Create enrichment proposal records in DB
        # For now, just log and return success
        
        logger.info(f"✅ {len(proposals)} enrichment proposals stored for instrument {instrumento_id}")
        
        return {
            "n_proposals": len(proposals),
            "status": "created"
        }
    
    @staticmethod
    def get_proposals(
        db: Session,
        instrumento_id: int,
        filter_status: Optional[str] = None
    ) -> List[dict]:
        """
        Retrieve enrichment proposals for review.
        
        Optional filter by estado_decision:
        - pendiente: awaiting approval
        - aceptada: approved
        - rechazada: rejected
        """
        # TODO: Query enrichment proposals from DB
        # For now, return empty list
        
        logger.info(f"✅ Enrichment proposals retrieved for instrument {instrumento_id}")
        
        return []
    
    @staticmethod
    def approve_proposals(
        db: Session,
        instrumento_id: int,
        decisions: Dict[int, str]
    ) -> dict:
        """
        Apply user decisions to enrichment proposals.
        
        decisions: {proposal_id: "aceptada" | "rechazada", ...}
        
        After approval:
        - Updates proposal estado_decision
        - Materializes accepted enrichments
        - Updates instrument state to "etl_aprobado"
        """
        from shared.models.instrumento_procesado import InstrumentoProcesado
        
        # Verify instrument exists and is in correct state
        instrumento = db.query(InstrumentoProcesado).filter(
            InstrumentoProcesado.instrumento_id == instrumento_id
        ).first()
        
        if not instrumento:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Instrument {instrumento_id} not found"
            )
        
        if instrumento.estado != "etl_pendiente_enriquecimiento":
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=f"Instrument must be in 'etl_pendiente_enriquecimiento' state. Current: {instrumento.estado}"
            )
        
        # TODO: Update proposal states in DB
        # TODO: Materialize accepted enrichments
        
        # Update instrument state
        instrumento.estado = "etl_aprobado"
        instrumento.fecha_procesamiento = datetime.now(timezone.utc)
        db.add(instrumento)
        db.commit()
        
        n_aceptadas = sum(1 for d in decisions.values() if d == "aceptada")
        n_rechazadas = sum(1 for d in decisions.values() if d == "rechazada")
        
        logger.info(
            f"✅ Enrichment approved for instrument {instrumento_id}: "
            f"{n_aceptadas} accepted, {n_rechazadas} rejected"
        )
        
        return {
            "n_aceptadas": n_aceptadas,
            "n_rechazadas": n_rechazadas
        }
    
    @staticmethod
    def get_summary(db: Session, instrumento_id: int) -> dict:
        """Get enrichment summary statistics"""
        
        return {
            "instrumento_id": instrumento_id,
            "n_total": 0,
            "n_pendiente": 0,
            "n_aceptada": 0,
            "n_rechazada": 0,
        }
