-- -- DATOS INICIALES: KPIS BY ADMINISTRATOR(LAYLA) -----------------------


INSERT INTO kpi (nombrekpi, descripcion, direccion_deseada, razon, formula) 
VALUES 
    ('Estatus de Acreditación y Rankings', 'El número y estatus de las acreditaciones, y la posición de una institución en distintos rankings educativos, puede ser un indicador importante de su reputación y calidad.', 'Aumentar', 'Más acreditaciones vigentes y mejor posición en rankings reflejan mayor reputación y calidad institucional.', 'Tasa_Acreditacion = num_accreditations_activas / num_accreditations_totales, Percentil_Ranking = (1 - (posicion_ranking / total_instituciones_en_ranking)) * 100'),
    ('Selectividad de Admisión', 'El porcentaje de solicitantes admitidos puede ser señal de la reputación y el atractivo de la institución. Una tasa de admisión más baja suele indicar mayor selectividad.', 'Disminuir', 'Una tasa de admisión más baja generalmente indica mayor selectividad y prestigio percibido.', 'Tasa_Admision (%) = (num_admitidos / num_solicitantes) * 100'),
    ('Tasa de Donación de Exalumnos', 'En instituciones de educación superior, la tasa a la que los exalumnos donan puede ser indicador de satisfacción a largo plazo y suele ser un componente crítico de los ingresos.', 'Aumentar', 'Una mayor tasa de donación refleja satisfacción sostenida de los exalumnos y fortalece los ingresos institucionales.', 'Tasa_Donacion_Exalumnos (%) = (num_alumni_donantes / num_alumni_totales) * 100'),
    ('Tasas de Asistencia', 'Las tasas de asistencia pueden ser un indicador temprano del compromiso y satisfacción del estudiante, y también se correlacionan con el éxito académico.', 'Aumentar', 'Mayor asistencia se asocia con mayor compromiso estudiantil y mejores resultados académicos.', 'Tasa_Asistencia (%) = (dias_asistidos_totales / dias_clase_programados_totales) * 100'),
    ('Tamaño Promedio de Clase', 'Este KPI mide el número promedio de estudiantes por clase, lo cual puede indicar el nivel de atención individual que cada estudiante puede recibir.', 'Disminuir', 'Clases más pequeñas suelen permitir mayor atención individualizada por estudiante.', 'Tamano_Promedio_Clase = num_estudiantes_totales / num_clases_totales'),
    ('Colegiatura Promedio', 'El costo promedio de la colegiatura puede indicar el posicionamiento de mercado del proveedor educativo. Colegiaturas más altas pueden significar posicionamiento premium, pero también pueden limitar el número de estudiantes potenciales.', 'Monitorear', 'El nivel adecuado depende del posicionamiento estratégico de la institución, no es inherentemente bueno subir o bajar sin contexto.', 'Colegiatura_Promedio = suma_colegiaturas_cobradas / num_estudiantes_totales'),
    ('Años Promedio hasta Graduación', 'El tiempo promedio que le toma a un estudiante completar su programa puede indicar la dificultad, flexibilidad y la capacidad de la institución para facilitar la graduación oportuna.', 'Disminuir', 'Un menor tiempo promedio hasta la graduación indica mayor eficiencia del programa y de la institución.', 'Anios_Promedio_Graduacion = suma_anios_hasta_graduacion_por_estudiante / num_graduados_totales'),
    ('Puntajes de Exámenes de Referencia', 'Los puntajes promedio de los estudiantes en exámenes de referencia como SAT, ACT, GMAT, etc., pueden señalar la capacidad académica del cuerpo estudiantil.', 'Aumentar', 'Puntajes más altos reflejan mayor capacidad académica del cuerpo estudiantil.', 'Puntaje_Promedio_Examen = suma_puntajes_examen / num_estudiantes_evaluados'),
    ('Estadísticas de Seguridad del Campus', 'Las medidas de seguridad del campus, como la tasa de delitos en el campus, pueden ser una medida crítica del bienestar estudiantil y pueden impactar la reputación de la institución.', 'Disminuir', 'Una menor tasa de incidentes de seguridad refleja un campus más seguro para la comunidad estudiantil.', 'Tasa_Delitos_Campus = (num_incidentes_seguridad / poblacion_campus_total) * 1000'),
    ('Razón de Consejeros por Estudiante', 'Este KPI en escuelas, especialmente a nivel bachillerato, puede indicar el nivel de apoyo disponible para los estudiantes en planeación académica, solicitudes universitarias y temas socioemocionales.', 'Disminuir', 'Una razón más baja (menos estudiantes por consejero) implica mayor disponibilidad de apoyo individual.', 'Razon_Consejero_Estudiante = num_estudiantes_totales / num_consejeros'),
    ('Tasa de Finalización de Cursos (Educación en Línea)', 'Similar a la tasa de deserción, este KPI es particularmente relevante para proveedores de educación en línea. Mide el porcentaje de estudiantes que completan un curso en línea respecto al total de inscritos.', 'Aumentar', 'Una mayor tasa de finalización indica mejor diseño y efectividad del curso en línea.', 'Tasa_Finalizacion_Online (%) = (num_estudiantes_que_completan_curso_online / num_estudiantes_inscritos_curso_online) * 100'),
    ('Razón de Inscripción a Finalización de Curso', 'El número de estudiantes que completan un curso comparado con los que se inscribieron. Una razón alta podría indicar que el contenido del curso es atractivo, el nivel de dificultad es apropiado y el curso aporta valor a los estudiantes.', 'Aumentar', 'Una razón más alta indica un curso más atractivo, con dificultad apropiada y de mayor valor percibido.', 'Razon_Inscripcion_Finalizacion = num_estudiantes_completan_curso / num_estudiantes_inscritos_curso'),
    ('Tasas de Incumplimiento en Préstamos Estudiantiles', 'Una tasa más baja indica que los egresados de la institución generalmente son financieramente estables tras graduarse, lo cual refleja positivamente el valor de la educación recibida.', 'Disminuir', 'Una menor tasa de incumplimiento refleja mejor estabilidad financiera de los egresados y mayor valor percibido de la educación.', 'Tasa_Incumplimiento_Prestamos (%) = (num_prestamos_en_default / num_prestamos_totales_otorgados) * 100'),
    ('Métricas de Diversidad', 'Las medidas de diversidad estudiantil y docente, incluyendo raza, género, nacionalidad, etc., pueden indicar la inclusividad de la institución y su atractivo para una demografía amplia.', 'Aumentar', 'Mayor diversidad refleja inclusividad institucional y mayor atractivo para una demografía amplia.', 'Proporcion_Diversidad_X (%) = (num_estudiantes_grupo_demografico_x / num_estudiantes_totales) * 100, Indice_Diversidad = num_grupos_demograficos_representados / num_estudiantes_totales'),
    ('Tasa de Deserción', 'Esta métrica representa el porcentaje de estudiantes que abandonan el programa antes de completarlo. Una tasa alta podría indicar insatisfacción con el programa, dificultad de los cursos u otros problemas institucionales.', 'Disminuir', 'Una menor tasa de deserción indica mayor satisfacción y menor cantidad de problemas institucionales o académicos.', 'Tasa_Desercion (%) = (num_estudiantes_que_abandonan / num_estudiantes_inscritos_totales) * 100'),
    ('Tamaño del Fondo Patrimonial (Endowment)', 'Para muchas instituciones de educación superior, el tamaño de su fondo patrimonial puede ser una medida clave de salud financiera y sostenibilidad.', 'Aumentar', 'Un fondo patrimonial más grande refleja mayor salud financiera y sostenibilidad institucional.', 'Fondo_Patrimonial_por_Estudiante = valor_total_fondo_patrimonial / num_estudiantes_totales'),
    ('Actividades Extracurriculares', 'El número y variedad de actividades extracurriculares disponibles para los estudiantes puede indicar el compromiso de la institución con la educación integral y el involucramiento estudiantil.', 'Aumentar', 'Mayor participación extracurricular refleja mayor compromiso institucional con la formación integral.', 'Tasa_Participacion_Extracurricular (%) = (num_estudiantes_participantes / num_estudiantes_totales) * 100'),
    ('Tasa de Publicación Docente', 'Para instituciones de educación superior y de investigación, la tasa a la que el profesorado publica artículos de investigación en revistas reconocidas puede ser una medida importante del rigor académico y enfoque de investigación de la institución.', 'Aumentar', 'Una mayor tasa de publicación refleja mayor rigor académico y enfoque en investigación.', 'Tasa_Publicacion_Docente = num_publicaciones_indexadas / num_profesores_investigadores'),
    ('Calificación del Profesorado y Tasa de Rotación', 'La calidad del profesorado juega un papel crítico en el éxito de cualquier institución educativa. Una menor tasa de rotación junto con mayor calificación docente puede indicar buena salud institucional.', 'Mixto', 'Se busca aumentar la proporción de profesores altamente calificados y, al mismo tiempo, disminuir la rotación docente.', 'Tasa_Calificacion_Docente (%) = (num_profesores_altamente_calificados / num_profesores_totales) * 100, Tasa_Rotacion_Docente (%) = (num_profesores_que_se_van / num_profesores_promedio_periodo) * 100'),
    ('Producción de Investigación Docente', 'El número y calidad de artículos académicos y otra producción de investigación del profesorado puede indicar el nivel intelectual y el prestigio de una institución, particularmente en educación superior.', 'Aumentar', 'Mayor producción y calidad de investigación docente refleja mayor prestigio institucional.', 'Produccion_Investigacion_por_Docente = num_publicaciones_totales / num_profesores_investigadores, Citas_Promedio_por_Publicacion = num_citas_totales / num_publicaciones_totales'),
    ('Tasa de Graduación', 'El porcentaje de estudiantes que completan su programa de estudios dentro de un periodo determinado. Una tasa de graduación alta puede señalar un currículo sólido y métodos de enseñanza efectivos.', 'Aumentar', 'Una mayor tasa de graduación refleja un currículo sólido y métodos de enseñanza efectivos.', 'Tasa_Graduacion (%) = (num_estudiantes_graduados_en_periodo / num_estudiantes_cohorte_inicial) * 100'),
    ('Convenios con la Industria y Oportunidades de Prácticas Profesionales', 'El número de convenios con la industria y de prácticas profesionales puede indicar las oportunidades prácticas para los estudiantes y la integración de la institución con el sector productivo.', 'Aumentar', 'Más convenios y vacantes de prácticas amplían las oportunidades prácticas para los estudiantes.', 'Tasa_Disponibilidad_Practicas (%) = (num_vacantes_practicas_ofrecidas / num_estudiantes_totales) * 100'),
    ('Gasto Instruccional por Estudiante Equivalente a Tiempo Completo (FTE)', 'Este KPI da información sobre cuánto invierte una institución en sus servicios instruccionales por estudiante, lo cual puede ser señal de calidad educativa.', 'Aumentar', 'Un mayor gasto instruccional por estudiante puede reflejar mayor inversión en calidad educativa.', 'Gasto_Instruccional_por_FTE = gasto_total_instruccional / num_estudiantes_fte'),
    ('Tasa de Colocación Laboral', 'Para muchas instituciones educativas, especialmente las vocacionales y de nivel superior, una medida crítica de éxito es el porcentaje de egresados que consiguen empleo en su área de estudio dentro de cierto plazo tras graduarse.', 'Aumentar', 'Una mayor tasa de colocación laboral refleja la efectividad de la institución para preparar a sus egresados.', 'Tasa_Colocacion_Laboral (%) = (num_graduados_empleados_en_su_area / num_graduados_totales) * 100'),
    ('Métricas de Interacción del Aprendiz (Plataformas en Línea)', 'Estas pueden incluir medidas como duración promedio de sesión, tasa de rebote, páginas por sesión, etc. Un mayor nivel de interacción generalmente es una señal positiva.', 'Mixto', 'Se busca aumentar la duración de sesión y las páginas por sesión, y disminuir la tasa de rebote.', 'Duracion_Promedio_Sesion = suma_duracion_sesiones / num_sesiones_totales, Tasa_Rebote (%) = (num_sesiones_una_sola_pagina / num_sesiones_totales) * 100, Paginas_por_Sesion = num_paginas_vistas_totales / num_sesiones_totales'),
    ('Recursos Bibliotecarios', 'El número y calidad de los recursos disponibles en la biblioteca de la institución, incluyendo libros, artículos de investigación y recursos digitales, puede indicar el apoyo a la excelencia académica.', 'Aumentar', 'Más recursos bibliotecarios por estudiante reflejan mayor apoyo a la excelencia académica.', 'Recursos_Bibliotecarios_por_Estudiante = num_recursos_bibliotecarios_totales / num_estudiantes_totales'),
    ('Valor de Vida del Estudiante', 'Este KPI ayuda a entender el ingreso total que un estudiante promedio genera a lo largo de su relación con la institución.', 'Aumentar', 'Un mayor valor de vida del estudiante refleja mayor rentabilidad de la relación institución-estudiante.', 'Valor_Vida_Estudiante = ingreso_promedio_anual_por_estudiante * duracion_promedio_relacion_anios'),
    ('Número de Programas Acreditados', 'El número de programas que han sido acreditados por organismos relevantes puede ser un indicador de la calidad institucional y el cumplimiento de estándares académicos.', 'Aumentar', 'Más programas acreditados reflejan mayor calidad institucional y cumplimiento de estándares académicos.', 'Proporcion_Programas_Acreditados (%) = (num_programas_acreditados / num_programas_totales) * 100'),
    ('Número de Cursos/Programas Ofrecidos', 'El rango de programas educativos que ofrece una institución puede ser señal de su adaptabilidad y capacidad para atender a un cuerpo estudiantil diverso.', 'Aumentar', 'Una oferta más amplia de programas refleja mayor adaptabilidad institucional.', 'Total_Programas_Ofrecidos = COUNT(num_cursos_o_programas_ofrecidos)'),
    ('Razón de Matrícula en Línea vs. Presencial', 'Con la creciente tendencia del aprendizaje digital, especialmente tras la pandemia de Covid-19, es importante analizar la capacidad de la institución para atraer y retener estudiantes en línea.', 'Monitorear', 'El balance ideal depende de la estrategia institucional respecto a modalidades en línea y presencial.', 'Razon_Online_Presencial = num_estudiantes_online / num_estudiantes_presenciales'),
    ('Convenios de Colaboración', 'Este KPI mide el número de convenios que una institución educativa tiene con otras instituciones o empresas. Puede ser señal de reconocimiento y demanda de la oferta de la institución.', 'Aumentar', 'Más convenios de colaboración reflejan mayor reconocimiento y demanda de la oferta institucional.', 'Total_Convenios_Activos = COUNT(num_convenios_activos)'),
    ('Tasa de Aprobación de Exámenes de Certificación', 'Para instituciones que ofrecen cursos que conducen a certificaciones profesionales, la tasa de aprobación puede ser una medida importante de la efectividad de sus programas.', 'Aumentar', 'Una mayor tasa de aprobación refleja mayor efectividad de los programas de certificación.', 'Tasa_Aprobacion_Certificacion (%) = (num_estudiantes_aprueban_examen / num_estudiantes_presentan_examen) * 100'),
    ('Patentes Otorgadas', 'Para instituciones de investigación, el número de patentes otorgadas es una medida importante de su productividad de investigación y capacidad de innovación.', 'Aumentar', 'Más patentes otorgadas reflejan mayor productividad de investigación y capacidad de innovación.', 'Patentes_por_Investigador = num_patentes_otorgadas / num_profesores_investigadores'),
    ('Porcentaje de Profesorado con Grado Terminal', 'Este KPI muestra la proporción de miembros del profesorado con el grado más alto en su campo (como un doctorado). Un porcentaje más alto puede ser indicador de la calidad del profesorado.', 'Aumentar', 'Un mayor porcentaje de doctores en el profesorado refleja mayor calidad docente.', 'Tasa_Grado_Terminal (%) = (num_profesores_con_doctorado / num_profesores_totales) * 100'),
    ('Porcentaje de Estudiantes de Medio Tiempo', 'La proporción de estudiantes que estudian medio tiempo puede dar información sobre la flexibilidad de los programas de la institución y la demografía de su cuerpo estudiantil.', 'Monitorear', 'El nivel adecuado depende de la estrategia de flexibilidad y del perfil demográfico objetivo de la institución.', 'Tasa_Medio_Tiempo (%) = (num_estudiantes_medio_tiempo / num_estudiantes_totales) * 100'),
    ('Porcentaje de Estudiantes que Reciben Ayuda Financiera', 'Esto puede indicar la accesibilidad de la institución para estudiantes de diversos contextos económicos.', 'Aumentar', 'Un mayor porcentaje de estudiantes con ayuda financiera refleja mayor accesibilidad económica de la institución.', 'Tasa_Ayuda_Financiera (%) = (num_estudiantes_con_ayuda_financiera / num_estudiantes_totales) * 100'),
    ('Tasa de Continuación de Estudios de Posgrado', 'La tasa a la que los egresados continúan con más estudios. Puede ser una medida clave para instituciones que ofrecen programas preuniversitarios o fundacionales.', 'Aumentar', 'Una mayor tasa de continuación a posgrado refleja el valor académico percibido del programa previo.', 'Tasa_Continuacion_Posgrado (%) = (num_graduados_continuan_estudios / num_graduados_totales) * 100'),
    ('Oportunidades de Desarrollo Profesional para el Profesorado', 'El alcance de las oportunidades de desarrollo profesional para el profesorado, como sabáticos, conferencias, becas de investigación, etc., puede indicar la calidad y satisfacción docente, lo cual afecta indirectamente los resultados estudiantiles.', 'Aumentar', 'Mayor participación en desarrollo profesional refleja mayor inversión institucional en la calidad docente.', 'Tasa_Participacion_Desarrollo_Profesional (%) = (num_profesores_participan_en_desarrollo_profesional / num_profesores_totales) * 100'),
    ('Tasa de Incidentes Disciplinarios', 'Este KPI mide el número de incidentes disciplinarios reportados en relación con el total del cuerpo estudiantil. Tasas más altas pueden sugerir problemas de cultura o gestión del campus.', 'Disminuir', 'Una menor tasa de incidentes disciplinarios refleja mejor cultura institucional y gestión del campus.', 'Tasa_Incidentes_Disciplinarios = (num_incidentes_disciplinarios / num_estudiantes_totales) * 1000'),
    ('Razón de Estudiantes Nacionales a Internacionales', 'Este KPI indica la capacidad de una institución para atraer estudiantes del extranjero, lo cual puede diversificar las fuentes de ingreso y mejorar la reputación de la institución.', 'Monitorear', 'El balance ideal depende de la estrategia de internacionalización de la institución.', 'Razon_Nacionales_Internacionales = num_estudiantes_nacionales / num_estudiantes_internacionales'),
    ('Financiamiento y Becas de Investigación', 'Particularmente importante en educación superior, este KPI representa el monto de financiamiento que recibe una institución para investigación. Indica la capacidad de investigación y la reputación de la institución.', 'Aumentar', 'Un mayor financiamiento de investigación refleja mayor capacidad de investigación y reputación institucional.', 'Financiamiento_Investigacion_por_Investigador = monto_total_financiamiento_investigacion / num_profesores_investigadores'),
    ('Ingresos por Educación Continua', 'Para instituciones que ofrecen educación continua, los ingresos derivados de estos programas pueden ser una medida de su capacidad para atraer y satisfacer las necesidades de estudiantes no tradicionales o de aprendizaje continuo.', 'Aumentar', 'Mayores ingresos por educación continua reflejan mayor capacidad para atender a estudiantes no tradicionales.', 'Proporcion_Ingresos_Educacion_Continua (%) = (ingresos_educacion_continua / ingresos_totales_institucion) * 100'),
    ('Ingresos por Licenciamiento y Patentes', 'Para universidades intensivas en investigación, los ingresos derivados de licenciar hallazgos de investigación o patentes pueden ser una fuente de ingreso importante y una señal de la fortaleza de investigación de la institución.', 'Aumentar', 'Mayores ingresos por licenciamiento y patentes reflejan mayor fortaleza de investigación institucional.', 'Proporcion_Ingresos_Licenciamiento (%) = (ingresos_licenciamiento_patentes / ingresos_totales_institucion) * 100'),
    ('Ingreso por Estudiante', 'Esto indica el ingreso promedio generado por cada estudiante. Ayuda a medir la efectividad de la estrategia de precios de la institución y el valor global que los estudiantes obtienen de los servicios educativos.', 'Aumentar', 'Un mayor ingreso por estudiante refleja mayor efectividad de la estrategia de precios y de valor institucional.', 'Ingreso_por_Estudiante = ingresos_totales_institucion / num_estudiantes_totales'),
    ('Número de Estudiantes Inscritos', 'Esto representa el número de estudiantes inscritos en una institución o programa. Es un indicador crítico de la demanda de la oferta de la institución e impacta directamente el potencial de ingresos.', 'Aumentar', 'Una mayor matrícula refleja mayor demanda de la oferta institucional y mayor potencial de ingresos.', 'Matricula_Total = SUM(num_estudiantes_inscritos)'),
    ('Disponibilidad de Vivienda Estudiantil', 'Para instituciones tradicionales con campus físico, el número de estudiantes que pueden alojarse en la vivienda del campus puede indicar la capacidad de la institución y su habilidad para atraer estudiantes residentes.', 'Aumentar', 'Mayor disponibilidad de vivienda refleja mayor capacidad institucional para atraer estudiantes residentes.', 'Tasa_Disponibilidad_Vivienda (%) = (num_camas_disponibles_dormitorios / num_estudiantes_totales) * 100'),
    ('Uso de Servicios de Salud Mental Estudiantil', 'La tasa a la que los estudiantes utilizan servicios de salud mental puede dar información sobre el bienestar del cuerpo estudiantil y la efectividad de los servicios de apoyo de la institución.', 'Monitorear', 'Un aumento puede reflejar tanto mayor necesidad como mejor acceso, se debe interpretar junto con otros indicadores de bienestar.', 'Tasa_Uso_Servicios_Salud_Mental (%) = (num_estudiantes_usan_servicios_salud_mental / num_estudiantes_totales) * 100'),
    ('Tasa de Retención Estudiantil', 'El porcentaje de estudiantes que se reinscriben periodo tras periodo. Tasas de retención altas pueden señalar la capacidad de la institución para brindar educación de calidad y buena satisfacción estudiantil, lo que puede llevar a una reputación sólida y crecimiento futuro de matrícula.', 'Aumentar', 'Una mayor retención refleja mejor calidad educativa y satisfacción estudiantil.', 'Tasa_Retencion (%) = (num_estudiantes_reinscritos_siguiente_periodo / num_estudiantes_elegibles_reinscripcion) * 100'),
    ('Puntajes de Satisfacción Estudiantil', 'Estos puntajes, generalmente obtenidos de encuestas, miden la satisfacción general de los estudiantes con su experiencia educativa. Puede cubrir aspectos del contenido del curso, calidad de enseñanza, servicios de apoyo e instalaciones del campus.', 'Aumentar', 'Puntajes de satisfacción más altos reflejan una mejor experiencia educativa integral.', 'Puntaje_Promedio_Satisfaccion = suma_puntajes_encuesta_satisfaccion / num_encuestas_respondidas'),
    ('Servicios de Apoyo Estudiantil', 'El alcance y calidad de los servicios de apoyo estudiantil, como orientación vocacional, tutorías, servicios de salud mental, etc., puede ser una medida importante de la satisfacción estudiantil y del apoyo institucional general.', 'Aumentar', 'Mayor uso de servicios de apoyo refleja mayor accesibilidad y valor percibido de dichos servicios.', 'Tasa_Utilizacion_Servicios_Apoyo (%) = (num_estudiantes_que_usan_servicios_apoyo / num_estudiantes_totales) * 100'),
    ('Razón de Estudiantes por Profesor', 'Esta métrica da información sobre la calidad de la educación impartida. Una razón más baja puede significar atención más personalizada para los estudiantes, lo que lleva a mejores resultados de aprendizaje.', 'Disminuir', 'Una razón más baja (menos estudiantes por profesor) permite mayor atención personalizada y mejores resultados de aprendizaje.', 'Razon_Estudiante_Profesor = num_estudiantes_totales / num_profesores_totales'),
    ('Tasa de Participación en Programas de Intercambio', 'La tasa a la que los estudiantes participan en programas de intercambio puede ser señal de las alianzas globales de la institución y de la amplitud de su experiencia educativa.', 'Aumentar', 'Mayor participación en intercambios refleja mayores alianzas globales y una experiencia educativa más amplia.', 'Tasa_Participacion_Intercambio (%) = (num_estudiantes_en_intercambio / num_estudiantes_totales) * 100'),
    ('Tasas de Transferencia', 'Para colegios comunitarios e instituciones similares, una medida clave de éxito es la tasa a la que los estudiantes se transfieren a instituciones de cuatro años.', 'Aumentar', 'Una mayor tasa de transferencia refleja la efectividad de la institución para preparar a sus estudiantes hacia estudios de cuatro años.', 'Tasa_Transferencia (%) = (num_estudiantes_transferidos_a_4anios / num_estudiantes_elegibles_transferencia) * 100'),
    ('Uso de Analítica de Aprendizaje', 'El grado en que una institución utiliza datos y analítica para mejorar la enseñanza y el aprendizaje puede ser señal de su innovación y compromiso con el logro académico.', 'Aumentar', 'Mayor adopción de analítica de aprendizaje refleja mayor innovación institucional y enfoque en el logro académico.', 'Tasa_Adopcion_Analitica_Aprendizaje (%) = (num_cursos_con_analitica_implementada / num_cursos_totales) * 100'),
    ('Crecimiento Interanual en Admisiones', 'Este KPI mide el cambio interanual en las nuevas admisiones de estudiantes. Un crecimiento rápido puede indicar demanda creciente de la oferta educativa de la institución.', 'Aumentar', 'Un crecimiento interanual positivo refleja demanda creciente de la oferta educativa institucional.', 'Crecimiento_Interanual_Admisiones (%) = ((num_admisiones_anio_actual - num_admisiones_anio_anterior) / num_admisiones_anio_anterior) * 100');


INSERT INTO variable (nombre_variable, nombre_display, unidad, tipo_dato) 
VALUES 
    ('num_accreditations_activas', 'Número de acreditaciones activas', 'conteo', 'entero'),
    ('num_accreditations_totales', 'Número de acreditaciones totales', 'conteo', 'entero'),
    ('posicion_ranking', 'Posición en el ranking', 'posición', 'entero'),
    ('total_instituciones_en_ranking', 'Total de instituciones en el ranking', 'conteo', 'entero'),
    ('num_admitidos', 'Número de admitidos', 'conteo', 'entero'),
    ('num_solicitantes', 'Número de solicitantes', 'conteo', 'entero'),
    ('num_alumni_donantes', 'Número de exalumnos donantes', 'conteo', 'entero'),
    ('num_alumni_totales', 'Número de exalumnos totales', 'conteo', 'entero'),
    ('dias_asistidos_totales', 'Días asistidos totales', 'conteo', 'entero'),
    ( 'dias_clase_programados_totales', 'Días de clase programados totales', 'conteo', 'entero'),
    ( 'num_estudiantes_totales', 'Número de estudiantes', 'conteo', 'entero'),
    ( 'num_clases_totales', 'Número de clases totales', 'conteo', 'entero'),
    ( 'suma_colegiaturas_cobradas', 'Suma de colegiaturas cobradas', 'moneda', 'decimal'),
    ( 'suma_anios_hasta_graduacion_por_estudiante', 'Suma de años hasta graduación por estudiante', 'años', 'decimal'),
    ( 'num_graduados_totales', 'Número de graduados totales', 'conteo', 'entero'),
    ( 'suma_puntajes_examen', 'Suma de puntajes de examen', 'puntos', 'decimal'),
    ( 'num_estudiantes_evaluados', 'Número de estudiantes evaluados', 'conteo', 'entero'),
    ( 'num_incidentes_seguridad', 'Número de incidentes de seguridad', 'conteo', 'entero'),
    ( 'poblacion_campus_total', 'Población total del campus', 'conteo', 'entero'),
    ( 'num_consejeros', 'Número de consejeros', 'conteo', 'entero'),
    ( 'num_estudiantes_que_completan_curso_online', 'Número de estudiantes que completan curso en línea', 'conteo', 'entero'),
    ( 'num_estudiantes_inscritos_curso_online', 'Número de estudiantes inscritos en curso en línea', 'conteo', 'entero'),
    ( 'num_estudiantes_completan_curso', 'Número de estudiantes que completan el curso', 'conteo', 'entero'),
    ( 'num_estudiantes_inscritos_curso', 'Número de estudiantes inscritos en el curso', 'conteo', 'entero'),
    ( 'num_prestamos_en_default', 'Número de préstamos en incumplimiento', 'conteo', 'entero'),
    ( 'num_prestamos_totales_otorgados', 'Número de préstamos totales otorgados', 'conteo', 'entero'),
    ( 'num_estudiantes_grupo_demografico_x', 'Número de estudiantes de un grupo demográfico', 'conteo', 'entero'),
    ( 'num_grupos_demograficos_representados', 'Número de grupos demográficos representados', 'conteo', 'entero'),
    ( 'num_estudiantes_que_abandonan', 'Número de estudiantes que abandonan', 'conteo', 'entero'),
    ( 'num_estudiantes_inscritos_totales', 'Número de estudiantes inscritos totales', 'conteo', 'entero'),
    ( 'valor_total_fondo_patrimonial', 'Valor total del fondo patrimonial (endowment)', 'moneda', 'decimal'),
    ( 'num_actividades_extracurriculares_ofrecidas', 'Número de actividades extracurriculares ofrecidas', 'conteo', 'entero'),
    ( 'num_estudiantes_participantes', 'Número de estudiantes participantes', 'conteo', 'entero'),
    ( 'num_publicaciones_indexadas', 'Número de publicaciones indexadas', 'conteo', 'entero'),
    ( 'num_profesores_investigadores', 'Número de profesores investigadores', 'conteo', 'entero'),
    ( 'num_profesores_altamente_calificados', 'Número de profesores altamente calificados', 'conteo', 'entero'),
    ( 'num_profesores_totales', 'Número de profesores totales', 'conteo', 'entero'),
    ( 'num_profesores_que_se_van', 'Número de profesores que se van', 'conteo', 'entero'),
    ( 'num_profesores_promedio_periodo', 'Número promedio de profesores en el periodo', 'conteo', 'decimal'),
    ( 'num_publicaciones_totales', 'Número de publicaciones totales', 'conteo', 'entero'),
    ( 'num_citas_totales', 'Número de citas académicas totales', 'conteo', 'entero'),
    ( 'num_estudiantes_graduados_en_periodo', 'Número de estudiantes graduados en el periodo', 'conteo', 'entero'),
    ( 'num_estudiantes_cohorte_inicial', 'Número de estudiantes de la cohorte inicial', 'conteo', 'entero'),
    ( 'num_convenios_industria_activos', 'Número de convenios con la industria activos', 'conteo', 'entero'),
    ( 'num_vacantes_practicas_ofrecidas', 'Número de vacantes de prácticas ofrecidas', 'conteo', 'entero'),
    ( 'gasto_total_instruccional', 'Gasto total instruccional', 'moneda', 'decimal'),
    ( 'num_estudiantes_fte', 'Número de estudiantes equivalentes a tiempo completo (FTE)', 'conteo', 'decimal'),
    ( 'num_graduados_empleados_en_su_area', 'Número de graduados empleados en su área', 'conteo', 'entero'),
    ( 'suma_duracion_sesiones', 'Suma de duración de sesiones', 'minutos', 'decimal'),
    ( 'num_sesiones_totales', 'Número de sesiones totales', 'conteo', 'entero'),
    ( 'num_sesiones_una_sola_pagina', 'Número de sesiones de una sola página', 'conteo', 'entero'),
    ( 'num_paginas_vistas_totales', 'Número de páginas vistas totales', 'conteo', 'entero'),
    ( 'num_recursos_bibliotecarios_totales', 'Número de recursos bibliotecarios totales', 'conteo', 'entero'),
    ( 'ingreso_promedio_anual_por_estudiante', 'Ingreso promedio anual por estudiante', 'moneda', 'decimal'),
    ( 'duracion_promedio_relacion_anios', 'Duración promedio de la relación (años)', 'años', 'decimal'),
    ( 'num_programas_acreditados', 'Número de programas acreditados', 'conteo', 'entero'),
    ( 'num_programas_totales', 'Número de programas totales', 'conteo', 'entero'),
    ( 'num_cursos_o_programas_ofrecidos', 'Número de cursos o programas ofrecidos', 'conteo', 'entero'),
    ( 'num_estudiantes_online', 'Número de estudiantes en línea', 'conteo', 'entero'),
    ( 'num_estudiantes_presenciales', 'Número de estudiantes presenciales', 'conteo', 'entero'),
    ( 'num_convenios_activos', 'Número de convenios activos', 'conteo', 'entero'),
    ( 'num_estudiantes_aprueban_examen', 'Número de estudiantes que aprueban el examen', 'conteo', 'entero'),
    ( 'num_estudiantes_presentan_examen', 'Número de estudiantes que presentan el examen', 'conteo', 'entero'),
    ( 'num_patentes_otorgadas', 'Número de patentes otorgadas', 'conteo', 'entero'),
    ( 'num_profesores_con_doctorado', 'Número de profesores con doctorado', 'conteo', 'entero'),
    ( 'num_estudiantes_medio_tiempo', 'Número de estudiantes de medio tiempo', 'conteo', 'entero'),
    ( 'num_estudiantes_con_ayuda_financiera', 'Número de estudiantes con ayuda financiera', 'conteo', 'entero'),
    ( 'num_graduados_continuan_estudios', 'Número de graduados que continúan estudios', 'conteo', 'entero'),
    ( 'num_profesores_participan_en_desarrollo_profesional', 'Número de profesores que participan en desarrollo profesional', 'conteo', 'entero'),
    ( 'num_incidentes_disciplinarios', 'Número de incidentes disciplinarios', 'conteo', 'entero'),
    ( 'num_estudiantes_nacionales', 'Número de estudiantes nacionales', 'conteo', 'entero'),
    ( 'num_estudiantes_internacionales', 'Número de estudiantes internacionales', 'conteo', 'entero'),
    ( 'monto_total_financiamiento_investigacion', 'Monto total de financiamiento para investigación', 'moneda', 'decimal'),
    ( 'ingresos_educacion_continua', 'Ingresos por educación continua', 'moneda', 'decimal'),
    ( 'ingresos_totales_institucion', 'Ingresos totales de la institución', 'moneda', 'decimal'),
    ( 'ingresos_licenciamiento_patentes', 'Ingresos por licenciamiento y patentes', 'moneda', 'decimal'),
    ( 'num_estudiantes_inscritos', 'Número de estudiantes inscritos', 'conteo', 'entero'),
    ( 'num_camas_disponibles_dormitorios', 'Número de camas disponibles en dormitorios', 'conteo', 'entero'),
    ( 'num_estudiantes_usan_servicios_salud_mental', 'Número de estudiantes que usan servicios de salud mental', 'conteo', 'entero'),
    ( 'num_estudiantes_reinscritos_siguiente_periodo', 'Número de estudiantes reinscritos en el siguiente periodo', 'conteo', 'entero'),
    ( 'num_estudiantes_elegibles_reinscripcion', 'Número de estudiantes elegibles para reinscripción', 'conteo', 'entero'),
    ( 'suma_puntajes_encuesta_satisfaccion', 'Suma de puntajes de encuesta de satisfacción', 'puntos', 'decimal'),
    ( 'num_encuestas_respondidas', 'Número de encuestas respondidas', 'conteo', 'entero'),
    ( 'num_estudiantes_que_usan_servicios_apoyo', 'Número de estudiantes que usan servicios de apoyo', 'conteo', 'entero'),
    ( 'num_estudiantes_en_intercambio', 'Número de estudiantes en intercambio', 'conteo', 'entero'),
    ( 'num_estudiantes_transferidos_a_4anios', 'Número de estudiantes transferidos a instituciones de 4 años', 'conteo', 'entero'),
    ( 'num_estudiantes_elegibles_transferencia', 'Número de estudiantes elegibles para transferencia', 'conteo', 'entero'),
    ( 'num_cursos_con_analitica_implementada', 'Número de cursos con analítica implementada', 'conteo', 'entero'),
    ( 'num_cursos_totales', 'Número de cursos totales', 'conteo', 'entero'),
    ( 'num_admisiones_anio_actual', 'Número de admisiones del año actual', 'conteo', 'entero'),
    ( 'num_admisiones_anio_anterior', 'Número de admisiones del año anterior', 'conteo', 'entero');

INSERT INTO kpi_variable (kpi_id, variable_id) 
VALUES 
    ('1', '1'),
    ('1', '2'),
    ('1', '3'),
    ('1', '4'),
    ('2', '5'),
    ('2', '6'),
    ('3', '7'),
    ('3', '8'),
    ('4', '9'),
    ('4', '10'),
    ('5', '11'),
    ('5', '12'),
    ('6', '13'),
    ('6', '11'),
    ('7', '14'),
    ('7', '15'),
    ('8', '16'),
    ('8', '17'),
    ('9', '18'),
    ('9', '19'),
    ('10', '11'),
    ('10', '20'),
    ('11', '21'),
    ('11', '22'),
    ('12', '23'),
    ('12', '24'),
    ('13', '25'),
    ('13', '26'),
    ('14', '27'),
    ('14', '11'),
    ('14', '28'),
    ('15', '29'),
    ('15', '30'),
    ('16', '31'),
    ('16', '11'),
    ('17', '33'),
    ('17', '11'),
    ('18', '34'),
    ('18', '35'),
    ('19', '36'),
    ('19', '37'),
    ('19', '38'),
    ('19', '39'),
    ('20', '40'),
    ('20', '41'),
    ('20', '35'),
    ('21', '42'),
    ('21', '43'),
    ('22', '44'),
    ('22', '45'),
    ('22', '11'),
    ('23', '46'),
    ('23', '47'),
    ('24', '48'),
    ('24', '15'),
    ('25', '49'),
    ('25', '50'),
    ('25', '51'),
    ('25', '52'),
    ('26', '53'),
    ('26', '11'),
    ('27', '54'),
    ('27', '55'),
    ('28', '56'),
    ('28', '57'),
    ('29', '58'),
    ('30', '59'),
    ('30', '60'),
    ('31', '61'),
    ('32', '62'),
    ('32', '63'),
    ('33', '64'),
    ('33', '35'),
    ('34', '65'),
    ('34', '37'),
    ('35', '66'),
    ('35', '11'),
    ('36', '67'),
    ('36', '11'),
    ('37', '68'),
    ('37', '15'),
    ('38', '69'),
    ('38', '37'),
    ('39', '70'),
    ('39', '11'),
    ('40', '71'),
    ('40', '72'),
    ('41', '73'),
    ('41', '35'),
    ('42', '74'),
    ('42', '75'),
    ('43', '76'),
    ('43', '75'),
    ('44', '75'),
    ('44', '11'),
    ('45', '77'),
    ('46', '78'),
    ('46', '11'),
    ('47', '79'),
    ('47', '11'),
    ('48', '80'),
    ('48', '81'),
    ('49', '82'),
    ('49', '83'),
    ('50', '84'),
    ('50', '11'),
    ('51', '11'),
    ('51', '37'),
    ('52', '85'),
    ('52', '11'),
    ('53', '86'),
    ('53', '87'),
    ('54', '88'),
    ('54', '89'),
    ('55', '90'),
    ('55', '91');



------------------------USUARIO ADMIN----------------------------
                        
INSERT INTO USUARIOS 
(usuario, password_hash )
VALUES
('admin','$2b$12$H4Bg4iZGDjpsCChc31lt2eWa8vmKaM6f.uydwSxhU/.f2WRvMFw6a');